export const employees = [
    {
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        department: 'Engineering',
        designation: 'Software Engineer',
        phoneNo: '123-456-7890',
        reportsTo: 'Jane Smith',
        dob: '1990-01-15',
        address: '123 Elm Street, Springfield, USA',
    },
    {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        email: 'jane.smith@example.com',
        department: 'Engineering',
        designation: 'Team Lead',
        phoneNo: '987-654-3210',
        reportsTo: 'Michael Johnson',
        dob: '1985-05-25',
        address: '456 Oak Street, Springfield, USA',
    },
    {
        id: 3,
        firstName: 'Michael',
        lastName: 'Johnson',
        email: 'michael.johnson@example.com',
        department: 'HR',
        designation: 'HR Manager',
        phoneNo: '555-123-4567',
        reportsTo: 'Sara Connor',
        dob: '1978-08-12',
        address: '789 Pine Avenue, Springfield, USA',
    },
    {
        id: 4,
        firstName: 'Sara',
        lastName: 'Connor',
        email: 'sara.connor@example.com',
        department: 'HR',
        designation: 'Senior HR Specialist',
        phoneNo: '444-987-6543',
        reportsTo: 'Emily Davis',
        dob: '1989-03-30',
        address: '321 Maple Lane, Springfield, USA',
    },
    {
        id: 5,
        firstName: 'Emily',
        lastName: 'Davis',
        email: 'emily.davis@example.com',
        department: 'Finance',
        designation: 'Accountant',
        phoneNo: '222-333-4444',
        reportsTo: 'Paul Brown',
        dob: '1993-11-19',
        address: '567 Cedar Road, Springfield, USA',
    },
    {
        id: 6,
        firstName: 'Paul',
        lastName: 'Brown',
        email: 'paul.brown@example.com',
        department: 'Finance',
        designation: 'Finance Manager',
        phoneNo: '111-555-6666',
        reportsTo: 'Nancy Taylor',
        dob: '1980-06-22',
        address: '890 Walnut Drive, Springfield, USA',
    },
    {
        id: 7,
        firstName: 'Nancy',
        lastName: 'Taylor',
        email: 'nancy.taylor@example.com',
        department: 'IT',
        designation: 'System Administrator',
        phoneNo: '333-777-8888',
        reportsTo: 'David Wilson',
        dob: '1995-02-10',
        address: '654 Birch Boulevard, Springfield, USA',
    },
    {
        id: 8,
        firstName: 'David',
        lastName: 'Wilson',
        email: 'david.wilson@example.com',
        department: 'IT',
        designation: 'IT Manager',
        phoneNo: '444-888-9999',
        reportsTo: 'Linda Clark',
        dob: '1975-09-07',
        address: '321 Redwood Lane, Springfield, USA',
    },
    {
        id: 9,
        firstName: 'Linda',
        lastName: 'Clark',
        email: 'linda.clark@example.com',
        department: 'Marketing',
        designation: 'Marketing Specialist',
        phoneNo: '222-111-3333',
        reportsTo: 'Robert Hall',
        dob: '1992-04-14',
        address: '123 Chestnut Court, Springfield, USA',
    },
    {
        id: 10,
        firstName: 'Robert',
        lastName: 'Hall',
        email: 'robert.hall@example.com',
        department: 'Marketing',
        designation: 'Marketing Manager',
        phoneNo: '999-000-1111',
        reportsTo: 'None',
        dob: '1983-12-03',
        address: '789 Aspen Way, Springfield, USA',
    },
];
